name: ci-kt-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs: 
  appplication-build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: gradlew permission
        run: chmod +x kt-example/gradlew
      - name: Build
        working-directory: kt-example 
        run: ./gradlew build
     
