name: ci-kt-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs: 
  appplication-build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: gradlew permission
        run: chmod +x kt-example/gradlew
      - name: Build
        working-directory: kt-example 
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: kt-example
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kt-server-example-ci_cd:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/kt-server-example-ci_cd:latest

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Kustomize
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_SHA: ${{ github.sha }}
        working-directory: kt-example/k8s
        run: kustomize edit set image kt-server=$DOCKER_USERNAME/kt-server-example-ci_cd:$GITHUB_SHA

      - name: Commit image update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github action"
          git commit -am "Update image:tag"

      - name: Push 
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: fgsantana/ci_cd-example
     
